apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
      release: v1
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
    - resources: 
      limits:
        memory: "128Mi"
        cpu: "500m" 

      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: "80"