apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: nginx-deployment-svc
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-app
  sessionAffinity: None
  type: ClusterIP