apiVersion: v1
kind: Pod
metadata:
  name: my-two-container-pod
  namespace: john-csi-demo
  labels:
    environment: dev
spec:
  containers:
      
  - name: server
    image: nginx:1.13-alpine
    ports:
      - containerPort: 80
        protocol: TCP
    resources: 
      - limits:
          memory: "128Mi"
          cpu: "500m" 

  - name: side-car
    image: alpine:latest
    command: ["/usr/bin/tail", "-f", "/dev/null"]
    resources: 
      - limits:
          memory: "128Mi"
          cpu: "500m" 

restartPolicy: Never
