apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: nginx-deployment-pvc-snapshot-1
spec:
  volumeSnapshotClassName: ibm-spectrum-scale-csi-volume-snapshot
  source:
    persistentVolumeClaimName: nginx-deployment-pvc