apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-lw
   annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs1"
    volDirBasePath: "spectrum-scale-csi-volume-store/lwdir"
reclaimPolicy: Delete
