apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset-dependent
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs1"
    clusterId: "5962258591020880994"
    uid: "1000"    
    gid: "1000"
    filesetType: "dependent"
    parentFileset: "fileset-independent-fset1"
reclaimPolicy: Delete

