apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-writer-deployment-pvc-snapshot-restore
  namespace: john-csi-demo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-remote-fileset