apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  - resources: 
      limits:
        memory: "128Mi"
        cpu: "500m" 
containers:
    - name: nginx-pod
      image: gcr.io/google_containers/nginx-slim:0.8
      ports:
      - name: web
        containerPort: 80
      securityContext:
        privileged: true
      volumeMounts:
      - name: nginx-vol1
        mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-vol1
        persistentVolumeClaim:
          claimName: nginx-pod-pvc 