kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: alpine
  namespace: john-busybox  
spec:
  replicas: 1
  strategy:
    type: Recreate    
  triggers:
    - type: ConfigChange
  
  selector:
    deploymentconfig: alpine
  template:
    metadata:
      labels:
        deploymentconfig: alpine
    spec:
      containers:
        - name: alpine
          image: alpine
          command:
            - /bin/sh
            - '-c'
            - while true ; do date; sleep 1; done;
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler