#oc import-image multitool --from=wbitt/network-multitool:openshift-extra --confirm
#oc import-image network-multitool --from=praqma/network-multitool:openshift-extra --confirm
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: multitool
  namespace: john-alpine
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: multitool
    spec:
      containers:
      - image: praqma/network-multitool:openshift-extra
        name: multitool
  triggers:
  - type: ConfigChange


 apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: multitool
  namespace: john-alpine
spec:
  selector:
    deploymentconfig: multitool
  replicas: 1
  template:
    metadata:
      labels:
        deploymentconfig: multitool
    spec:
      containers:
#      - image: wbitt/network-multitool:openshift-extra
      - image: praqma/network-multitool:openshift-extra
        name: multitool
#        command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
        imagePullPolicy: Always
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
        - multitool
      from:
        kind: ImageStreamTag
        name: 'network-multitool:latest'
    type: ImageChange
  strategy:
    type: Rolling
 