#oc import-image multitool --from=wbitt/network-multitool:openshift-extra --confirm
#oc import-image network-multitool --from=praqma/network-multitool:openshift-extra --confirm
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: multitool
  namespace: john-alpine
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: multitool
    spec:
      containers:
      - image: praqma/network-multitool:openshift-extra
        name: multitool
  triggers:
  - type: ConfigChange 